AmaliTech-Training-Academy/Memory_Game

memory-game/starter-code/src/js/modules/setup.js
file structure to organize files
=> source file for game logic

memory-game/starter-code/modules/app.js
start game functionality chasis added
=> #1 start game function added

memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/services.js
we have a Game class with all methods for game functionality
=> game blueprint

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/user_input.js
Method for setting user theme updated
=> user theme method updated

memory-game/starter-code/css/style.css, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/user_input.js
User interface for 4 by 4 mode updated
=> design updated

memory-game/starter-code/css/style.css
=> User interface style for grid

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/user_input.js
Set game information panel user interface for solo player
=> setting solo player

memory-game/starter-code/css/style.css, memory-game/starter-code/modules/app.js
functionality to reset game to initial settings when a user clicks the "new game" button
=> new game functionality

memory-game/starter-code/modules/js/user_input.js
set number of player info at the bottom
=> multiplayer bottom panel

memory-game/starter-code/modules/app.js
Timer functionality for solo player
=> timer functionality

memory-game/starter-code/css/style.css, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/game_mechanics.js, memory-game/starter-code/modules/js/user_input.js
hover functionality at start page
=> hover effect at start page

memory-game/starter-code/css/style.css
Styling of "start game" page and hover effect on all pages
=> overall hover effect and start game styling

memory-game/starter-code/css/style.css, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/game_mechanics.js
functionality to count players move
=> move count

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/js/user_input.js
when a node is clicked, an icon or number is revealed depend on theme choice
=> game logic and icons update

memory-game/starter-code/css/style.css
Modified code for mobile responsiveness(Home)
=> update mobile responsiveness

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/game_mechanics.js
Player turn indication and game play result when game play is over
=> player turn and result screen

memory-game/starter-code/css/style.css
removed unrelated characters from css
=> style updated

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/app.js
set up new game and  reset function updated
=> result pop function updated

memory-game/starter-code/css/style.css
Changes made to "section width" for tablet responsiveness
=> Responsiveness

memory-game/starter-code/modules/app.js, memory-game/starter-code/modules/js/game_mechanics.js
Timer function is called once a user starts to play game
=> timer updated

memory-game/starter-code/css/style.css, memory-game/starter-code/modules/app.js
refreshes on "new game" button click
=> new game function updated

memory-game/starter-code/css/style.css
Responsiveness for tablet screen
=> tablet responsiveness

memory-game/starter-code/css/style.css
style update for tablet screen size
=> style update

memory-game/starter-code/css/style.css, memory-game/starter-code/index.html, memory-game/starter-code/modules/app.js
mobile responsiveness style and modal screen
=> mobile responsiveness
